# config.yaml
rawCsvDir: "./raw_csv"          # Relative path to the folder containing raw CSV files.
archivePath: "./archive"        # Path where successfully processed files will be moved.
failedPath: "./failed"          # Path where files with errors will be moved.
fileRegex: ".*\\.csv$"          # Regular expression to match CSV files.
dryRun: false                   # Set to true for a dry-run (files won't be moved).
logLevel: "debug"               # Winston log level.
logFile: "sss-etl-app.log"              # Log file name.
database:
  connectionString: "postgres://postgres:saltmeadow-sss@localhost:5432/sss_etl_db"
# Additional settings for the parser factory if needed.
fileTypeRegexes:
  trax: "order"
  itemz: "item(s)?"
platforms:
  uber:
    type: "uber"
    writeIsolated: true
    expectedHeaders:
      - "Store"
      - "External Store ID"
      - "Country"
      - "Country Code"
      - "City"
      - "Order ID"
      - "Order UUID"
      - "Order Status"
      - "Delivery Status"
      - "Scheduled?"
      - "Completed?"
      - "Online Order?"
      - "Canceled By"
      - "Menu Item Count"
      - "Currency Code"
      - "Ticket Size"
      - "Date Ordered"
      - "Time Customer Ordered"
      - "Cancellation Time"
      - "Time Merchant Accepted"
      - "Time to Accept"
      - "Original Prep Time"
      - "Prep Time Increased?"
      - "Increased Prep Time"
      - "Courier Arrival Time"
      - "Time Courier Started Trip"
      - "Time Courier Delivered"
      - "Total Delivery Time"
      - "Courier Wait Time (Restaurant)"
      - "Courier Wait Time (Eater)"
      - "Total Prep & Handoff Time"
      - "Order Duration"
      - "Delivery Batch Type"
      - "Fulfillment Type"
      - "Order Channel"
      - "Eats Brand"
      - "Subscription Pass"
      - "Workflow UUID"
  square:
    type: "square"
    writeIsolated: true
    expectedHeaders:
      - "Date"
      - "Time"
      - "Time Zone"
      - "Gross Sales"
      - "Discounts"
      - "Service Charges"
      - "Net Sales"
      - "Gift Card Sales"
      - "Tax"
      - "Tip"
      - "Partial Refunds"
      - "Total Collected"
      - "Source"
      - "Card"
      - "Card Entry Methods"
      - "Cash"
      - "Square Gift Card"
      - "Other Tender"
      - "Other Tender Type"
      - "Tender Note"
      - "Fees"
      - "Net Total"
      - "Transaction ID"
      - "Payment ID"
      - "Card Brand"
      - "PAN Suffix"
      - "Device Name"
      - "Staff Name"
      - "Staff ID"
      - "Details"
      - "Description"
      - "Event Type"
      - "Location"
      - "Dining Option"
      - "Customer ID"
      - "Customer Name"
      - "Customer Reference ID"
      - "Device Nickname"
      - "Third Party Fees"
      - "Deposit ID"
      - "Deposit Date"
      - "Deposit Details"
      - "Fee Percentage Rate"
      - "Fee Fixed Rate"
      - "Refund Reason"
      - "Discount Name"
      - "Transaction Status"
      - "Cash App"
      - "Order Reference ID"
      - "Fulfillment Note"
      - "Free Processing Applied"
      - "Channel"
      - "Unattributed Tips"
  slice:
    type: "slice"
    writeIsolated: true
    expectedHeaders:
      - "Order #"
      - "Order Date"
      - "Customer"
      - "Order Type"
      - "Subtotal"
      - "Prepaid Tip"
      - "Tax"
      - "Order Total"
      - "Status"
